### Get all
GET http://localhost:8080/identity

### Create user
POST http://localhost:8080/identity
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Login (Create session)
POST http://localhost:8080/session/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Validate session
GET http://localhost:8080/session/validate
Cookie: sessionId=521513cb-3e07-4aaa-a69e-f416c00a50df

### Get User
GET http://localhost:8080/identity/152e7883-4a5a-4be6-8602-a685f04fafa3

### Change User
PUT http://localhost:8080/identity/152e7883-4a5a-4be6-8602-a685f04fafa3
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Delete User
DELETE  http://localhost:8080/identity/152e7883-4a5a-4be6-8602-a685f04fafa3